### ISSUE TITLE
Add status 'down' to each service in a pipeline

### ISSUE THREAD

**Issue by fr0gs** [big-data-europe/mu-swarm-admin-service#23]
When a new pipeline is launched, it is created in the DB with a status and a repository linked and I assume the mu-swarm-admin-service will query the git repository and will add triples per each service on that pipeline

If possible I'd need that when the service triples are added into the DB for a given pipeline, each service to have an initial status of 'down'. 

This is needed to provide a more fine-grained control over the running services in a pipeline and to improve the UX.

**Comment by cecton** [comment]
Fixed by 0e6c2bc0c77561b319d2bf25a43843b6cf2a38cd
